#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=GA-Trust
#SBATCH --mail-type=FAIL
#SBATCH --mem=500gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --nodelist=xcnf9
python run_genetic_algorithm.py