#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Valence_1
#SBATCH --mail-type=FAIL
#SBATCH --mem=500gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --nodelist=xcnf7
python run_genetic_algorithm.py