#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --job-name=Softmax
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=junyili@u.nus.edu
#SBATCH --mem=100gb
#SBATCH --partition=normal
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --nodelist=xcnf[0-5,7-8,11-12,14-21]
python run_softmax.py