#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Coverage_0.2
#SBATCH --mail-type=FAIL
#SBATCH --mem=300gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --nodelist=xcnf16
python run_baseline.py