#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=Coverage
#SBATCH --mail-type=FAIL
#SBATCH --mem=400gb
#SBATCH --partition=long
#SBATCH --cpus-per-task=50
#SBATCH --ntasks=1
#SBATCH --nodelist=xcnf9
srun python run_coverage.py